# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20200307_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
